### ISSUE TITLE
vjs can't run on window 10

### ISSUE THREAD

**Issue by wynalh** [yazz/visualjavascript#33]
I downloaded the vjs.exe binary code,and when i run it with admin privilege on window 10 x64 os,i got this error,why?
```
E:\vjs>vjs
Setting up Visual Javascript to run for the first time. Please wait a few minutes...
{ Error: EPERM: operation not permitted, mkdir 'E:\'
    at Object.mkdirSync (fs.js:757:3)
    at mkdirpNativeSync (C:\snapshot\visualjavascript\node_modules\mkdirp\lib\mkdirp-native.js:25:17)
    at Function.mkdirpSync [as sync] (C:\snapshot\visualjavascript\node_modules\mkdirp\index.js:21:7)
    at Object.<anonymous> (C:\snapshot\visualjavascript\src\electron.js:138:24)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
    at Function.Module._load (internal/modules/cjs/loader.js:583:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12) errno: -4048, syscall: 'mkdir', code: 'EPERM', path: 'E:\\' }
pkg/prelude/bootstrap.js:1244
      throw error;
      ^

Error: Cannot find module 'E:\node_modules\sqlite3'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:634:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:560:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\snapshot\visualjavascript\src\db_helper.js:18:35)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:651:32)
```

**Comment by wynalh** [comment]
install sqlite3 manually
